# Generated by Django 4.2.2 on 2023-09-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='alternative_phone',
        ),
    ]
