# Generated by Django 4.2.2 on 2023-11-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_images_delete_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
    ]
