# Generated by Django 4.2.2 on 2023-11-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_images_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image10',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image11',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image3',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image4',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image5',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image6',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image7',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image8',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image9',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
