# Generated by Django 4.2.2 on 2023-11-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_images_image10_images_image11_images_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image12',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
