# Generated by Django 4.2.2 on 2023-11-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_alter_email_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
