# Generated by Django 4.2.2 on 2023-11-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_email_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='email',
            new_name='gmail1',
        ),
    ]
