# Generated by Django 4.2.2 on 2023-11-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_rename_email_gmail1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmail1',
            name='name',
        ),
    ]
