# Generated by Django 4.2.2 on 2023-11-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_remove_gmail1_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
